version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: messenger
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://app:app@db:5432/messenger?schema=public
      JWT_SECRET: dev-secret
      NODE_ENV: production
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - public_data:/app/public

volumes:
  db_data:
  public_data: